Minor edits
ECSIM/gopem pull request #152
Opened 2023-08-23 03:01 UTC by sadrasabouri

#### What does this implement/fix? Explain your changes.
- `Dependencies` section removed from `README.md`
- `setup.cfg` removed

2023-08-23 21:45 UTC, sepandhaghighi requested changes

2023-08-23 21:45 UTC, sepandhaghighi commented on CHANGELOG.md
> +### Changed
Two `### Changed` sections

2023-08-23 23:56 UTC, sadrasabouri commented on CHANGELOG.md
> +### Changed
Done.

2023-08-24 11:39 UTC, sepandhaghighi approved these changes
🚀

2023-08-24 11:39 UTC, merged